## Домашнее задание №1

### Задача 1:

Оформляйте ноутбук, используя эти советы:
1. Номер задачи - заголовок
2. Номер подзадачи - заголовок
3. Предоставленные наборы данных оформляйте, как код

### Задача 2:

_**На складе лежат разные фрукты в разном количестве.
Нужно написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе, при помощи использования kwargs**_

In [4]:
def total(**kwargs):
    total = sum (kwargs.values())
    return total

print('Общее количество фруктов на складе =', total (яблоки = 7, бананы = 3, манго = 6, мандарины = 9, персики = 2, хурма = 8))

Общее количество фруктов на складе = 35

### Задача 3:
_**Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты**_

[100, 125, -90, 345, 655, -1, 0, 200]

_**Используйте list comprehensions**_

In [5]:
adv_cost = [100, 125, -90, 345, 655, -1, 0, 200]

In [6]:
correct_adv_cost = [i for i in adv_cost if i >= 0]
print ('Список без отрицательных сумм: ', correct_adv_cost)
print('Суммарные затраты =', sum(correct_adv_cost))

Список без отрицательных сумм:  [100, 125, 345, 655, 0, 200]
Суммарные затраты = 1425

### Задача 4:
_**Даны два списка.**_
- _**Дата покупки**_

['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']

- _**Суммы покупок по датам**_

[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

In [9]:
date = ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']

In [10]:
revenue = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

### Найти 4.1 
_**Найдите, какая выручка у компании в ноябре.**_  
Используйте list comprehensions

In [11]:
print('Выручка компании в ноябре =', sum(revenue[i] for i in range(len(revenue)) if '-11-' in date[i]))

Выручка компании в ноябре = 25098

### Найти 4.2   
_**Найдите выручку компании в зависимости от месяца.**_  
Для этого напишите функцию, которая на вход принимает список с датами и список с выручкой, а на выходе словарь, где ключи - это месяцы, а значения - это выручка.  
Используйте аннотирование типов.

In [12]:
def transform_months (d: list, r: list) -> dict:
    result = {}
    m_name = ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь']
    m_txt = ['-01-', '-02-', '-03-', '-04-', '-05-', '-06-', '-07-', '-08-', '-09-', '-10-', '-11-', '-12-']
    for m in range(12):
        r_s = sum(revenue[i] for i in range(len(r)) if m_txt[m] in d[i])
        result.update({m_name[m] : r_s })
    return(result)

print ('Выручка по месяцам:\n', transform_months (date, revenue))

Выручка по месяцам:
 {'январь': 0, 'февраль': 0, 'март': 0, 'апрель': 0, 'май': 0, 'июнь': 0, 'июль': 0, 'август': 0, 'сентябрь': 25647, 'октябрь': 28645, 'ноябрь': 25098, 'декабрь': 45452}